### ISSUE TITLE
The close guard is missing in edit/new state.

### ISSUE THREAD

**Issue by glyad** [LogoFX/Samples.Specifications#6]
Then I edit new or existed record and click to window close button, the application is closed without a confirmation. In my opinion, it's a good use case sample to specification, since it one of the frequently tested problems in real applications.

The expected behavior is following:
Then [I click Windows close button ("x") or application "Close" button] and I have unapplied changes in the form, I want to see a guard message.
There are three options with a guard message box expected:
1. Save == to save changes and close the app;
2. Don't Save == exit without to save;
3. Cancel == do not exit.

Interesting case: what should happen, if I press "Save" and have invalid data, or I press "Save", but the save operation is failed?

**Comment by godrose** [comment]
Added with correspondent specs
